//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlkUniversity.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlkUniversity_dbEntities : DbContext
    {
        public AlkUniversity_dbEntities()
            : base("name=AlkUniversity_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<module> module { get; set; }
        public virtual DbSet<operation> operation { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<role_operation> role_operation { get; set; }
        public virtual DbSet<schedules> schedules { get; set; }
        public virtual DbSet<states> states { get; set; }
        public virtual DbSet<subjects> subjects { get; set; }
        public virtual DbSet<teachers> teachers { get; set; }
        public virtual DbSet<user_subject> user_subject { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
