//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlkUniversity.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class subjects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public subjects()
        {
            this.user_subject = new HashSet<user_subject>();
        }
    
        public int id { get; set; }
        [Required]
        [StringLength(30, ErrorMessage = "{0} must be at least {2} characters", MinimumLength = 2)]
        [Display(Name = "Name")]
        public string name { get; set; }
        public Nullable<int> schedule_id { get; set; }
        [Required]
        [StringLength(255)]
        [Display(Name = "Description")]
        public string description { get; set; }
        public Nullable<int> teacher_id { get; set; }
        [Required]
        [MaxLength(4)]
        [Display(Name = "Maximum students")]
        public Nullable<int> max_student { get; set; }
    
        public virtual schedules schedules { get; set; }
        public virtual teachers teachers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_subject> user_subject { get; set; }
    }
}
