//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlkUniversity.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class teachers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public teachers()
        {
            this.subjects = new HashSet<subjects>();
        }
        [Display(Name = "Teacher")]
        public int id { get; set; }
        [Required]
        [StringLength(30, ErrorMessage = "{0} must be at least {2} characters", MinimumLength = 2)]
        [Display(Name = "Name")]
        public string name { get; set; }
        [Required]
        [StringLength(30, ErrorMessage = "{0} must be at least {2} characters", MinimumLength = 2)]
        [Display(Name = "Lastname")]
        public string lastname { get; set; }
        [Required]
        [StringLength(8, ErrorMessage = "{0} must be at least {2} characters", MinimumLength = 8)]
        [Display(Name = "DNI")]
        public string dni { get; set; }
        [Required]
        public Nullable<int> state_id { get; set; }
    
        public virtual states states { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subjects> subjects { get; set; }
    }
}
