//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlkUniversity.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users()
        {
            this.user_subject = new HashSet<user_subject>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        [Required]
        [StringLength(8,ErrorMessage = "{0} must be at least {1} characters", MinimumLength =8)]
        [Display(Name ="DNI")]
        public string dni { get; set; }
        public string file { get; set; }
        public Nullable<int> role_id { get; set; }
    
        public virtual role role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_subject> user_subject { get; set; }
    }
}
